name: protein-expression-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-image
  - opencv
  - tifffile
  - cellpose
  - pip
  - pip:
      - trackpy