name: protein-expression-env
channles:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.6
  - numpy=2.0.2
  - pandas=2.2.3
  - matplotlib=3.9.4
  - seaborn=0.13.2
  - scipy=1.13.1
  - tifffile=2024.8.30
  - imageio=2.37.0
  - tqdm=4.67.1
  - pillow=11.1.0
  - python-dateutil=2.9.0.post0
  - pyparsing=3.2.3
  - packaging=24.2
  - fonttools=4.57.0
  - cycler=0.12.1
  - kiwisolver=1.4.7
  - importlib-resources=6.5.2
  - tzdata=2025.2
  - pytz=2025.2
  - contourpy=1.3.0
  - wheel=0.37.0
  - six=1.15.0
  - setuptools=58.0.4
  - pip=21.2.4
  - future=0.18.2
  - altgraph=0.17.2
  - macholib=1.15.2