name: protein-expression-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.6
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - tifffile
  - imageio
  - tqdm
  - pillow
  - scikit-learn
  - pip
  - pip:
      - trackpy